annotations:
  charts.openshift.io/name: Argo CD Agent - Principal Component
apiVersion: v2
appVersion: v0.8.1
description: Argo CD Agent Principal component for multi-cluster application management
home: https://github.com/argoproj-labs/argocd-agent
keywords:
- argocd
- gitops
- agent
kubeVersion: '>=1.24.0-0'
maintainers:
- name: Argo Project Maintainers
  url: https://github.com/argoproj-labs/argocd-agent
name: argocd-agent-principal
sources:
- https://github.com/argoproj-labs/argocd-agent
type: application
version: 0.3.4
