apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd-agent-principal.fullname" . }}
  namespace: {{ .Values.principal.namespace }}
  labels:
    app.kubernetes.io/name: argocd-agent-principal
